# Generated by Django 3.2.25 on 2025-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=256)),
                ('pokemon_type1', models.CharField(choices=[('Normal', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Fighting', 'Fighting'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy')], max_length=8)),
                ('pokemon_type2', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Fighting', 'Fighting'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy')], max_length=8, null=True)),
                ('total_stats', models.IntegerField(blank=True)),
                ('pokemon_HP', models.IntegerField(blank=True)),
                ('attack', models.IntegerField(blank=True)),
                ('defense', models.IntegerField(blank=True)),
                ('special_attack', models.IntegerField(blank=True)),
                ('special_defense', models.IntegerField(blank=True)),
                ('speed', models.IntegerField(blank=True)),
                ('generation', models.PositiveSmallIntegerField(choices=[(1, 'Generation I'), (2, 'Generation II'), (3, 'Generation III'), (4, 'Generation IV'), (5, 'Generation V'), (6, 'Generation VI')], default=1, help_text='Which main-series generation this Pokémon debuted in')),
                ('legendary', models.BooleanField(default=False, help_text='True if this Pokémon is legendary')),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
                'ordering': ['generation', 'pokemon_name'],
            },
        ),
    ]
