# Generated by Django 3.2.25 on 2025-06-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_HP',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_attack',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_defense',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='total_stats',
            field=models.PositiveIntegerField(),
        ),
    ]
